### ISSUE TITLE
hdf5 folder is empty in pre-preocessed dataset

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [dragonlong/articulated-pose#14]
Hi, thanks for sharing your work. I tried to download the `preprocessed dataset`, but the `hdf5` folder seems to be empty, is that mean to be empty? Thanks!

**Comment by dragonlong** [comment]
Hi Linfang, 

Yes, since the hdf5 files are quite big(>200G) to be hosted on Google drive, we encourage the users to using Pybullet to render RGB-D images from CAD models, then use the provided preprocessing code to generate hdf5 files, which contains depth point cloud and canonical coordinates. 

Best,
Xiaolong

**Comment by Jianghanxiao** [comment]
Hi,

I wonder the estimated size for each category. Is 200 G for all categories, or just for eyeglasses

**Comment by Lynne-Zheng-Linfang** [comment]
> Hi Linfang,
> 
> Yes, since the hdf5 files are quite big(>200G) to be hosted on Google drive, we encourage the users to using Pybullet to render RGB-D images from CAD models, then use the provided preprocessing code to generate hdf5 files, which contains depth point cloud and canonical coordinates.
> 
> Best,
> Xiaolong

Thanks!
